//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKiosk.BService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BService.IKioskService")]
    public interface IKioskService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKioskService/AuthenticateUser", ReplyAction="http://tempuri.org/IKioskService/AuthenticateUserResponse")]
        bool AuthenticateUser(string UserName, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKioskServiceChannel : BKiosk.BService.IKioskService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KioskServiceClient : System.ServiceModel.ClientBase<BKiosk.BService.IKioskService>, BKiosk.BService.IKioskService {
        
        public KioskServiceClient() {
        }
        
        public KioskServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KioskServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KioskServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KioskServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AuthenticateUser(string UserName, string Password) {
            return base.Channel.AuthenticateUser(UserName, Password);
        }
    }
}
