//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKiosk.BService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BetteryMember", Namespace="http://schemas.datacontract.org/2004/07/WebRole1.HelperClasses")]
    [System.SerializableAttribute()]
    public partial class BetteryMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BatteriesCheckedOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BatteriesInPlanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerProfileIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MemberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OutstandingCreditField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BatteriesCheckedOut {
            get {
                return this.BatteriesCheckedOutField;
            }
            set {
                if ((this.BatteriesCheckedOutField.Equals(value) != true)) {
                    this.BatteriesCheckedOutField = value;
                    this.RaisePropertyChanged("BatteriesCheckedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BatteriesInPlan {
            get {
                return this.BatteriesInPlanField;
            }
            set {
                if ((this.BatteriesInPlanField.Equals(value) != true)) {
                    this.BatteriesInPlanField = value;
                    this.RaisePropertyChanged("BatteriesInPlan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerProfileID {
            get {
                return this.CustomerProfileIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerProfileIDField, value) != true)) {
                    this.CustomerProfileIDField = value;
                    this.RaisePropertyChanged("CustomerProfileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberFirstName {
            get {
                return this.MemberFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberFirstNameField, value) != true)) {
                    this.MemberFirstNameField = value;
                    this.RaisePropertyChanged("MemberFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemberID {
            get {
                return this.MemberIDField;
            }
            set {
                if ((this.MemberIDField.Equals(value) != true)) {
                    this.MemberIDField = value;
                    this.RaisePropertyChanged("MemberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberLastName {
            get {
                return this.MemberLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberLastNameField, value) != true)) {
                    this.MemberLastNameField = value;
                    this.RaisePropertyChanged("MemberLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OutstandingCredit {
            get {
                return this.OutstandingCreditField;
            }
            set {
                if ((this.OutstandingCreditField.Equals(value) != true)) {
                    this.OutstandingCreditField = value;
                    this.RaisePropertyChanged("OutstandingCredit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BService.IKioskService")]
    public interface IKioskService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKioskService/AuthenticateUser", ReplyAction="http://tempuri.org/IKioskService/AuthenticateUserResponse")]
        BKiosk.BService.BetteryMember AuthenticateUser(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKioskService/AddBetteryMember", ReplyAction="http://tempuri.org/IKioskService/AddBetteryMemberResponse")]
        bool AddBetteryMember(string FirstName, string LastName, string Email, string Password, string Zipcode, bool GetEmails, int SubscriptionPlan);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKioskServiceChannel : BKiosk.BService.IKioskService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KioskServiceClient : System.ServiceModel.ClientBase<BKiosk.BService.IKioskService>, BKiosk.BService.IKioskService {
        
        public KioskServiceClient() {
        }
        
        public KioskServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KioskServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KioskServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KioskServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BKiosk.BService.BetteryMember AuthenticateUser(string UserName, string Password) {
            return base.Channel.AuthenticateUser(UserName, Password);
        }
        
        public bool AddBetteryMember(string FirstName, string LastName, string Email, string Password, string Zipcode, bool GetEmails, int SubscriptionPlan) {
            return base.Channel.AddBetteryMember(FirstName, LastName, Email, Password, Zipcode, GetEmails, SubscriptionPlan);
        }
    }
}
